version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
            USER_UID: 1000
            USER_GID: 1000
            VARIANT: 16

    init: true
    volumes:
        - /var/run/docker.sock:/var/run/docker-host.sock
        - ..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    network_mode: service:cosmos
  cosmos:
    container_name: cosmos-contoso-real-estate
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    mem_limit: 3g
    cpu_count: 2
    environment:
        AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
        AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    volumes:
        # Forwards the local Docker socket to the container.
        - /var/run/docker.sock:/var/run/docker-host.sock
