/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */

import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {},
});
